language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

install:
  - npm install

# before_script:
#   - git config user.name "NavePnow"
#   - git config user.email "evan.wong.stu@gmail.com"
#   - sed -i'' "s~https://github.com/<yourname>/<reponame>.git~https://${GITHUB_ACCESS_TOKEN}@github.com/<yourname>/<reopname>.git~" _config.yml
script:
  - hexo douban
  - hexo clean
  - hexo g
  - hexo d

after_script:
  - cd ./public
  - git init
  - git config user.name "NavePnow"
  - git config user.email "evan.wong.stu@gmail.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/

notifications:
  email:
    - work@evanwong.me
  on_success: change
  on_failure: always

